name: in_app_rate
version: "1.0.0"
description: "A Flutter plugin that lets you show a review pop up where users can leave a review for your app"
repository: "https://github.com/surfstudio/flutter-in-app-rate"
issue_tracker: "https://github.com/surfstudio/flutter-in-app-rate/issues"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.in_app_rate
        pluginClass: InAppRatePlugin
      ios:
        pluginClass: InAppRatePlugin

custom:
  is_stable: false
  unstable_version:
  is_plugin: true
  path: in_app_rate
  separate_repo_url:
  hostUrl:
